[project]
name = "python-package-template"
version = "0.1.0"
dependencies = [
    "cookiecutter>=2.1.0"
]

[dependency-groups]
dev = [
    "pytest>=7.0.0"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v"
