{% if cookiecutter.include_docker == "y" -%}
services:
  {{ cookiecutter.project_slug }}:
    build: .
    container_name: {{ cookiecutter.project_slug }}
    volumes:
      - .:/app
    environment:
      - TERM=xterm-256color
    command: ["--alpaca", "happy", "--color", "green", "Hello from Docker! 🐳"]
{%- endif %}
